//
//  NPS.swift
//
//  File Generated by vicentecantugarcia on 05/24/2019.
//  Using model_gen.py
//

import ObjectMapper

class NPS: Mappable {

	var activity_views: Int!
	var days_since_signup: Int!
	var user_plan: String!
	var build: NPS_Build!
	var id: Int!
	var nps: Int!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		activity_views <- map["activity_views"]
		days_since_signup <- map["days_since_signup"]
		user_plan <- map["user_plan"]
		build <- map["build"]
		id <- map["id"]
		nps <- map["nps"]
	}
    
}

class NPS_Build: Mappable {

	var release_date: Date!
	var version: String!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		release_date <- (map["release_date"], CustomDateFormatTransform(formatString: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"))
		version <- map["version"]
	}
}

